# needed so messages are sent together with error codes
server.error.include-message=always

server.tomcat.threads.max=4
server.tomcat.threads.min-spare=1

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 5min hopefully
security.jwt.expiration-time=300000
