name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2 # or specify a version like mariadb:11.5.2
        env:
          MYSQL_DATABASE: my_database # Name of the database to create
          MYSQL_USER: my_user         # Database username
          MYSQL_PASSWORD: my_password  # Database user password
        ports:
          - 3306:3306 # Expose the database port

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MariaDB to be ready
        run: |
            for i in {1..30}; do
              if mysqladmin ping -h "127.0.0.1" --user=my_user --password=my_password --silent; then
                echo "MariaDB is ready!"
                break
              fi
              echo "Waiting for MariaDB..."
              sleep 5
            done

      - name: Check MariaDB connection
        run: |
          mysql -h 127.0.0.1 -u my_user -p'my_password' -e 'SELECT 1;' || { echo "Database connection failed!"; exit 1; }

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
