name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..3}; do
            if mysqladmin ping -h 127.0.0.1 --user=test_user --password=test_password --silent; then
              echo "MariaDB is ready!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 5
          done

      - name: Check MariaDB connection
        run: |
          mysql -h mariadb -u test_user -p 'test_password' -e 'SELECT 1;' || { echo "Database connection failed!"; exit 1; }

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
