name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: my_user          # Set your user
          MYSQL_PASSWORD: my_password  # Set your password
        options: >-
          --health-cmd="mysqladmin ping -h localhost --user=my_user --password=my_password" 
          --health-interval=10s
          --health-timeout=5s 
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Change to '17' since your setup mentioned JDK 17
          distribution: 'temurin'
          cache: maven

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h "127.0.0.1" --user=my_user --password=my_password --silent; then
              echo "MariaDB is ready!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 5
          done

      - name: Check MariaDB connection
        run: |
          mysql -h 127.0.0.1 -u my_user -pmy_password testdb || { echo "Database connection failed!"; exit 1; }

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
