name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Change to '17' since your setup mentioned JDK 17
          distribution: 'temurin'
          cache: maven

      # Prüfen, ob MariaDB erreichbar ist
      - name: Check MariaDB Connection
        run: |
          echo "Checking MariaDB connection..."
          for i in {1..2}; do
            if mysql -h 127.0.0.1 -P 3306 -u testuser -ptestpassword -e "SELECT 1" testdb; then
              echo "MariaDB is reachable!"
              break
            else
              echo "MariaDB is not reachable yet. Retrying in 5 seconds..."
              sleep 5
            fi
          done


      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
