name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: homeautomation_test
          MYSQL_USER: pipeline_user
          MYSQL_PASSWORD: pipeline_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Change to '17' since your setup mentioned JDK 17
          distribution: 'temurin'
          cache: maven

      # Prüfen, ob MariaDB erreichbar ist
      - name: Check MariaDB Connection
        run: |
          echo "Checking MariaDB connection..."
          for i in {1..2}; do
            if mysql -h 127.0.0.1 -P 3306 -u pipeline_user -ppipeline_password -e "SELECT 1" homeautomation_test; then
              echo "MariaDB is reachable!"
              break
            else
              echo "MariaDB is not reachable yet. Retrying in 5 seconds..."
              sleep 5
            fi
          done
      - name: Display database configuration
        run: |
          echo "Displaying the database configuration..."
          cat config/properties.config.test  # Dieser Befehl zeigt den Inhalt der Datei an

      - name: Configure database connection for CI
        run: |
          echo "Setting up database configuration for CI environment..."
          echo "runner.db.url=localhost:3306/homeautomation_test" >> config/properties.config.test
          echo "runner.db.user=pipeline_user" >> config/properties.config.test
          echo "runner.db.pw=pipeline_password" >> config/properties.config.test

      - name: Display database configuration
        run: |
          echo "Displaying the database configuration..."
          cat config/properties.config.test  # Dieser Befehl zeigt den Inhalt der Datei an 

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
