name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: homeautomation_test
          MYSQL_USER: pipeline_user
          MYSQL_PASSWORD: pipeline_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Change to '17' since your setup mentioned JDK 17
          distribution: 'temurin'
          cache: maven

      # Prüfen, ob MariaDB erreichbar ist
      - name: Check MariaDB Connection
        run: |
          echo "Checking MariaDB connection..."
          for i in {1..5}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SELECT 1"; then
              echo "MariaDB is reachable!"
              break
            else
              echo "MariaDB is not reachable yet. Retrying in 5 seconds..."
              sleep 5
            fi
          done

      - name: Configure database connection for CI
        run: |
          echo "Setting up database configuration for CI environment..."
          echo "" >> config/properties.config.test
          echo "runner.db.url=localhost:3306/homeautomation_test" >> config/properties.config.test
          echo "runner.db.user=root" >> config/properties.config.test
          echo "runner.db.pw=root" >> config/properties.config.test
          
          echo "" >> config/properties.config
          echo "runner.db.url=localhost:3306/homeautomation_test" >> config/properties.config
          echo "runner.db.user=root" >> config/properties.config
          echo "runner.db.pw=root" >> config/properties.config

      - name: Check if database exists
        run: |
          if mysql -h 127.0.0.1 -u root -proot -e "USE homeautomation_test"; then
          echo "Datenbank homeautomation_test existiert bereits."
          else
          echo "Datenbank homeautomation_test existiert nicht. Erstelle die Datenbank..."
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE homeautomation_test"
          echo "Datenbank homeautomation_test wurde erstellt."
          fi
          

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
