name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.5.2
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Change to '17' since your setup mentioned JDK 17
          distribution: 'temurin'
          cache: maven

      - name: Wait for MariaDB to be ready
        run: |
            echo "Waiting for MariaDB to be healthy..."
            until docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q mariadb) | grep -q "healthy"; do
              sleep 2
            done
            echo "MariaDB is ready!"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml
